### ISSUE TITLE
`get` and `search` not working in es>=6.0

### ISSUE THREAD

**Issue by mwilliammyers** [elastic-rs/elastic#331]
This might be related to #330...

version: `0.21.0-pre.1`  
<br>

If I index documents using `bulk` (and probably with `index` etc. too) like:
```rust
#[derive(Serialize, Deserialize, ElasticType, Debug)]
#[elastic(index = "test")]
pub struct MyType {
    timestamp: ChronoDateTime,
}

let ops = (0..1000).into_iter().map(|i| {
    bulk::<MyType>().index(MyType {
        timestamp: "2019-02-18T00:00:00Z".parse().unwrap(),
    })
});

let response = client.bulk().extend(ops).send()?;
```

querying the new documents via `search` or `get` like:
```rust
client
    .search::<MyType>()
    .body(json!({ "query": { "match_all": {} } }))
    .send()?;
```
produces an error:
```
error sending a request or receiving a response. 
Caused by: error receiving a response. 
Status code: 200 OK
```  
<br>
<br>

However, manually building the request works:
```rust
client
    .request(SimpleSearchRequest::for_index_ty(MyType::static_index(), MyType::static_ty()))
    .send()?
    .into_response::<SearchResponse<Value>>()?;
```

Also, not sure if this is supposed to work, but it produces the same error:
```rust
client
    .request(SimpleSearchRequest::for_index_ty(MyType::static_index(), MyType::static_ty()))
    .send()?
    .into_response::<SearchResponse<MyType>>()?;

**Comment by KodrAus** [comment]
Thanks for the report! Our support for ES 6.0 is in its very first stages, and unfortunately it looks like it doesn't really work yet...

I'll add your example as an integration test so we can fix this up.

**Comment by mwilliammyers** [comment]
Cool, thanks! I might try to see if I can fix this and my other issues and open a PR?

**Comment by KodrAus** [comment]
Please feel free! We haven't had a lot of outside contributions to the client itself yet so if you find the code hard to navigate please reach out. If it looks like too much effort then I'll try fix this up, probably sometime this week.

**Comment by KodrAus** [comment]
I think the problem here was the `bulk` request indexing documents incorrectly. I've opened a PR that should fix this, but the error message you're getting back is a bit unhelpful, so I'll see if we can improve that.

**Comment by mwilliammyers** [comment]
Yeah, I was thinking about a way to improve logging and I saw there was an old issue about it...

**Comment by mwilliammyers** [comment]
I am still having issues with this even after #333.

This does not work:
```
client
    .search::<MyType>()
    .index(MyType::static_index())
    .ty(MyType::static_ty())
    .send()?;
```

but this does:
```
use serde_json::Value;

client
    .search::<Value>()
    .index(MyType::static_index())
    .ty(MyType::static_ty())
    .send()?;
```

**Comment by KodrAus** [comment]
Hmm, are you targetting the `master` branch now rather than what's on crates.io?

**Comment by mwilliammyers** [comment]
Yeah.

I think I figured it out - my graphql crate was swallowing the errors and (I think) creating those cryptic error messages... It is because I had an `id` field on my type but `_source` doesn't have an `id` field.

**Comment by KodrAus** [comment]
Glad you figured it out! I've published a new prerelease on crates.io that includes the fix for this.
